Fixing issue 306 : do some change in systemId handling for xjc 2.3.4+
highsource/jaxb-tools pull request #329
Opened 2023-08-25 09:13 UTC by laurentschoelens

Better handling of issue #244 which was partial fixed in previous PR and lead to #306 new issue.

Rollback of initial change in #244.
Only present resolved SystemId to DomForest if initial systemId does not exists.
Logs in overriden `getSystemId` in debug mode to indicate change in systemId presented if caller is `DOMForest` and if initial systemId points to a file which doesn't exisits.

Extra change :
`MavenCatalogResolver` : Changing log format (adding class name)

2023-08-25 10:12 UTC, michael-o requested changes
Will test this next week on the whole project.

One nit: you can safely drop the prefix `x2tc-proxy`, it is from my project which bears no meaning to the actual test project.

2023-08-25 10:12 UTC, michael-o commented on maven-plugin/tests/pom.xml
> +    <module>jt-306</module>
Indent?

2023-08-25 10:43 UTC, laurentschoelens commented
> 

I just wanted to get the project as near as your config in it. If you want me to change the xsd naming files to "obfuscate" it, I can

2023-08-25 10:43 UTC, laurentschoelens commented
> Will test this next week on the whole project.
> 
> One nit: you can safely drop the prefix `x2tc-proxy`, it is from my project which bears no meaning to the actual test project.

I just wanted to get the project as near as your config in it. If you want me to change the xsd naming files to "obfuscate" it, I can

2023-08-25 10:55 UTC, michael-o commented
> > Will test this next week on the whole project.
> > One nit: you can safely drop the prefix `x2tc-proxy`, it is from my project which bears no meaning to the actual test project.
> 
> I just wanted to get the project as near as your config in it. If you want me to change the xsd naming files to "obfuscate" it, I can

Yes, please do so. The hierarchy is important,  not the naming.

2023-08-25 11:24 UTC, laurentschoelens commented
> > > Will test this next week on the whole project.
> > > One nit: you can safely drop the prefix `x2tc-proxy`, it is from my project which bears no meaning to the actual test project.
> > 
> > 
> > I just wanted to get the project as near as your config in it. If you want me to change the xsd naming files to "obfuscate" it, I can
> 
> Yes, please do so. The hierarchy is important, not the naming.

Done.
Naming was /important/ due to catalog resolution 😄 Removed all ref to `x2tc-proxy`

2023-08-25 13:38 UTC, michael-o approved these changes
Tried on the real project. It works, no errors, not even warnings. Thanks for the quick turnaround.

2023-08-28 14:46 UTC, mattrpav approved these changes
Applying work around for jaxb-tools. v2.0.5

Opened jaxb-ri ticket to provide better fix, and allow jaxb-tools to remove the work around

2023-08-28 14:46 UTC, merged